use_frameworks!
platform :ios, '9.3'

pod 'SwiftLint'

target 'WolfCore_Example' do
    pod 'WolfCore', '~> 2.1'
    # pod 'WolfCore', :path => '../'

    target 'WolfCore_Tests' do
        inherit! :search_paths
    end
end
